# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('background', models.ImageField(upload_to='')),
                ('top_picture', models.ImageField(upload_to='')),
                ('side_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('confirmation_hash', models.CharField(max_length=128)),
                ('confirmed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='petition',
            name='signatures',
            field=models.ManyToManyField(to='petition.Signature'),
        ),
    ]
