# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='signatures',
        ),
        migrations.AddField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='petition.Petition'),
            preserve_default=False,
        ),
    ]
