# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_squashed_0002_petition_org_twitter_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_sender',
            field=models.CharField(default='petition@antipub.org', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_smtp_host',
            field=models.CharField(default='localhost', max_length=100),
        ),
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_smtp_port',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_smtp_smarttls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_smtp_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='confirmation_email_smtp_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_subscribe_mail_smtp_host',
            field=models.CharField(default='localhost', max_length=100),
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_subscribe_mail_smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_subscribe_mail_smtp_port',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_subscribe_mail_smtp_smarttls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_subscribe_mail_smtp_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='newsletter_subscribe_mail_smtp_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
