# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_auto_20180308_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='confirmation_email_smtp_smarttls',
            new_name='confirmation_email_smtp_starttls',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='newsletter_subscribe_mail_smtp_smarttls',
            new_name='newsletter_subscribe_mail_smtp_starttls',
        ),
    ]
