# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_auto_20170929_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='background',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='petition',
            name='side_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='top_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
