# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_auto_20171008_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='target',
            field=models.BigIntegerField(blank=True, null=500),
        ),
    ]
