# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_auto_20180308_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='footer_text',
            field=tinymce.models.HTMLField(default='This petition is hosted on RAP website.'),
        ),
    ]
