# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_petition_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='target',
            field=models.IntegerField(default=500),
        ),
    ]
