# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_auto_20180804_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=tinymce.models.HTMLField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Petition', verbose_name='Petition'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='subscribed_to_mailinglist',
            field=models.BooleanField(default=False, verbose_name='Subscribed to mailing list'),
        ),
    ]
