# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-15 06:51
from __future__ import unicode_literals

from django.db import migrations

from html import unescape
from bs4 import BeautifulSoup

def myescape(html_text):
    strings = []
    soup = BeautifulSoup(html_text, 'html.parser')
    return str(soup.prettify(formatter="html5"))

def myunescape(html_text):
    strings = []
    soup = BeautifulSoup(html_text, 'html.parser')
    for tag in soup.find_all():
        for s in tag.strings:
            strings.append(s)
    for s in strings:
        try:
            s.replace_with(unescape(s))
        except:
            pass
    return str(soup)


def htmlUnescapePetition(apps, schema_editor):
    Petition = apps.get_model('petition', 'Petition')
    for p in Petition.objects.all():
        newtitle = myunescape(p.title)
        newtext = myunescape(p.text)
        p.title = newtitle
        p.text = newtext
        p.save()


def htmlEscapePetition(apps, schema_editor):
    Petition = apps.get_model('petition', 'Petition')
    for p in Petition.objects.all():
        newtitle = myescape(p.title)
        newtext = myescape(p.text)
        p.title = newtitle
        p.text = newtext
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_auto_20180911_1857'),
    ]

    operations = [
        migrations.RunPython(htmlUnescapePetition, htmlEscapePetition),
    ]
