# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_auto_20171008_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
