# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 15:39
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

def createPytitionUsers(apps, schema_editor):
	PytitionUser = apps.get_model('petition', 'PytitionUser')
	User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
	for u in User.objects.all():
		print("Creating PU for User \'{}\'".format(u.first_name))
		pu = PytitionUser.objects.create()
		pu.user = u
		pu.save()

def destroyPytitionUsers(apps, schema_editor):
	PytitionUser = apps.get_model('petition', 'PytitionUser')
	for pu in PytitionUser.objects.all():
		pu.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0006_auto_20180924_1738'),
    ]

    operations = [
	migrations.RunPython(createPytitionUsers, destroyPytitionUsers),
    ]
