# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0007_auto_20171009_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='side_text',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
