# Generated by Django 2.2.2 on 2019-09-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0007_auto_20190807_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='confirmation_email_sender',
            new_name='confirmation_email_reply',
        ),
        migrations.RenameField(
            model_name='petitiontemplate',
            old_name='confirmation_email_sender',
            new_name='confirmation_email_reply',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='confirmation_email_smtp_host',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='confirmation_email_smtp_password',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='confirmation_email_smtp_port',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='confirmation_email_smtp_starttls',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='confirmation_email_smtp_tls',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='confirmation_email_smtp_user',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='use_custom_email_settings',
        ),
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_host',
        ),
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_password',
        ),
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_port',
        ),
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_starttls',
        ),
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_tls',
        ),
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_user',
        ),
    ]
