# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:10
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0008_auto_20171009_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='bgcolor',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='petition',
            name='linear_gradient_direction',
            field=models.CharField(blank=True, choices=[('NO', 'no gradient'), ('R', 'to right'), ('B', 'to bottom'), ('BR', 'to bottom right'), ('BL', 'to bottom left')], default='NO', max_length=2),
        ),
    ]
