# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0008_auto_20180924_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytitionuser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pytitionuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
