# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0009_auto_20171010_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='mobile_background',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
