# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0009_auto_20181120_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_modify_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
