# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0009_auto_20180925_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_members', models.BooleanField()),
                ('can_remove_members', models.BooleanField()),
                ('can_create_petitions', models.BooleanField()),
                ('can_modify_petitions', models.BooleanField()),
                ('can_delete_petitions', models.BooleanField()),
                ('can_view_signatures', models.BooleanField()),
                ('can_modify_signatures', models.BooleanField()),
                ('can_delete_signatures', models.BooleanField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='pytitionuser',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='user', to='petition.Permission'),
        ),
    ]
