# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:31
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0010_petition_mobile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='gradient_from',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='petition',
            name='gradient_to',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
    ]
