# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0010_auto_20181007_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytitionuser',
            name='invitations',
            field=models.ManyToManyField(blank=True, related_name='invited', to='petition.Organization'),
        ),
    ]
