# Generated by Django 2.2.16 on 2021-05-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0010_auto_20200902_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='message')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='petition',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Petition')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.ModerationReason')),
            ],
        ),
    ]
