# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-01 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0011_auto_20181201_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='can_add_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_create_petitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_delete_petitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_delete_signatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_modify_petitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_modify_signatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_remove_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_view_signatures',
            field=models.BooleanField(default=False),
        ),
    ]
