# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0011_auto_20171010_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='linear_gradient_direction',
            field=models.CharField(blank=True, choices=[('no gradient', 'no gradient'), ('to right', 'to right'), ('to bottom', 'to bottom'), ('to bottom right', 'to bottom right'), ('to bottom left', 'to bottom left')], default='no gradient', max_length=2),
        ),
    ]
