# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0012_auto_20181022_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitiontemplate',
            name='confirmation_email_sender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_host',
            field=models.CharField(blank=True, default='localhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='confirmation_email_smtp_port',
            field=models.IntegerField(blank=True, default=25),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='footer_text',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='newsletter_subscribe_mail_smtp_host',
            field=models.CharField(blank=True, default='localhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='org_twitter_handle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='target',
            field=models.IntegerField(blank=True),
        ),
    ]
