# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0013_auto_20181022_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitiontemplate',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
