# Generated by Django 2.2.28 on 2022-08-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0013_auto_20210607_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='has_share_buttons',
            field=models.BooleanField(default=True),
        ),
    ]
