# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0013_auto_20181202_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
