# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:47
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0013_auto_20171010_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='footer_text',
            field=tinymce.models.HTMLField(default='Cette pétition est hébergée sur le site de RAP.'),
        ),
    ]
