# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0014_petition_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='footer_links',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
