# Generated by Django 2.2.28 on 2022-08-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0014_petition_has_share_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_share_buttons',
            field=models.BooleanField(default=True),
        ),
    ]
