# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0014_auto_20181022_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='petition.PetitionTemplate', verbose_name='Default petition template'),
        ),
    ]
