# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0015_petition_footer_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='petition',
            name='twitter_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
