# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-31 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0015_auto_20190130_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='use_custom_email_settings',
            field=models.BooleanField(default=False),
        ),
    ]
