# Generated by Django 2.2.28 on 2022-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0016_signature_uses_phone_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
