# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-02 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0016_petition_use_custom_email_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='background',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='mobile_background',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='top_picture',
        ),
    ]
