# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0016_auto_20171010_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='subscribed_to_mailinglist',
            field=models.BooleanField(default=False),
        ),
    ]
