# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0017_petitiontemplate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='petition.PetitionTemplate', to_field='id', verbose_name='Default petition template'),
        ),
        migrations.AlterField(
            model_name='pytitionuser',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='petition.PetitionTemplate', to_field='id', verbose_name='Default petition template'),
        ),
    ]
