# Generated by Django 2.1.5 on 2019-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0017_auto_20190202_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_create_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_modify_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='use_custom_email_settings',
            field=models.BooleanField(default=False),
        ),
    ]
