# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0017_signature_subscribed_to_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signature',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
