# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0018_auto_20181031_1329'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='petitiontemplate',
            index_together=set([('id',)]),
        ),
    ]
