# Generated by Django 2.1.5 on 2019-02-03 20:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0018_auto_20190203_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitiontemplate',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
