# Generated by Django 2.2.28 on 2022-12-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0018_petition_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='show_publication_date',
            field=models.BooleanField(default=False),
        ),
    ]
