# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0019_auto_20181031_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.PetitionTemplate', to_field='id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.PytitionUser')),
            ],
        ),
    ]
