# Generated by Django 4.2.7 on 2023-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0019_petition_show_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='has_email_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='has_facebook_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='has_linkedin_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='has_mastodon_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='has_tumblr_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='has_twitter_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='has_whatsapp_share_button',
            field=models.BooleanField(default=False),
        ),
    ]
