# Generated by Django 2.1.5 on 2019-02-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0019_petitiontemplate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='ipaddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
