# Generated by Django 3.2 on 2023-02-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0019_petition_show_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='linked_petitions',
            field=models.ManyToManyField(related_name='_petition_petition_linked_petitions_+', to='petition.Petition'),
        ),
        migrations.CreateModel(
            name='CampaignProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.organization')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.pytitionuser')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='campaign_proposals',
            field=models.ManyToManyField(blank=True, null=True, through='petition.CampaignProposal', to='petition.Petition'),
        ),
        migrations.AddField(
            model_name='pytitionuser',
            name='campaign_proposals',
            field=models.ManyToManyField(blank=True, null=True, through='petition.CampaignProposal', to='petition.Petition'),
        ),
    ]
