# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0020_templateownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='petition_templates',
        ),
    ]
