# Generated by Django 2.1.5 on 2019-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0020_signature_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='salt',
            field=models.TextField(blank=True),
        ),
    ]
