# Generated by Django 3.2 on 2023-02-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0020_auto_20230224_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignproposal',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='petition.organization'),
        ),
        migrations.AlterField(
            model_name='campaignproposal',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='petition.pytitionuser'),
        ),
    ]
