# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0020_petition_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='newsletter_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='petition',
            name='newsletter_subscribe_http_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='petition',
            name='newsletter_subscribe_mail_subject',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='petition',
            name='newsletter_subscribe_method',
            field=models.CharField(choices=[('MAIL', 'MAIL'), ('POST', 'POST'), ('GET', 'GET')], default='MAIL', max_length=4),
        ),
    ]
