# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0021_auto_20180202_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='sign_form_footer',
            field=models.TextField(blank=True),
        ),
    ]
