# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0021_remove_organization_petition_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='petition_templates',
            field=models.ManyToManyField(blank=True, through='petition.TemplateOwnership', to='petition.PetitionTemplate', verbose_name='Petition templates'),
        ),
    ]
