# Generated by Django 2.1.5 on 2019-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0021_petition_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='slugs',
            field=models.ManyToManyField(to='petition.SlugModel'),
        ),
    ]
