# Generated by Django 4.2.7 on 2023-12-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0021_auto_20231203_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='has_share_buttons',
        ),
    ]
