# Generated by Django 4.2.7 on 2023-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0022_remove_petition_has_share_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_email_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_facebook_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_linkedin_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_mastodon_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_tumblr_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_twitter_share_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='has_whatsapp_share_button',
            field=models.BooleanField(default=False),
        ),
    ]
