# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0022_petition_sign_form_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='org_twitter_handle',
            field=models.CharField(default='@RAP_Asso', max_length=20),
            preserve_default=False,
        ),
    ]
