# Generated by Django 2.1.5 on 2019-03-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0022_auto_20190327_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slugs',
        ),
        migrations.AddField(
            model_name='organization',
            name='slugname',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
