# Generated by Django 4.2.7 on 2023-12-08 12:21

from django.db import migrations


def set_new_petition_template_share_fields(apps, schema_editor):
    PetitionTemplate = apps.get_model('petition', 'PetitionTemplate')
    for pt in PetitionTemplate.objects.all():
        if pt.has_share_buttons:
            pt.has_email_share_button = True
            pt.has_facebook_share_button = True
            pt.has_tumblr_share_button = True
            pt.has_linkedin_share_button = True
            pt.has_twitter_share_button = True
            pt.has_mastodon_share_button = True
            pt.has_whatsapp_share_button = True
            pt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0023_petitiontemplate_has_email_share_button_and_more'),
    ]

    operations = [
        migrations.RunPython(set_new_petition_template_share_fields)
    ]
