# Generated by Django 4.2.7 on 2023-12-09 06:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0024_auto_20231208_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitiontemplate',
            name='has_share_buttons',
        ),
    ]
