# Generated by Django 4.2.7 on 2023-12-09 06:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('petition', '0025_remove_petitiontemplate_has_share_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='zip_code',
            field=models.CharField(max_length=5)
        ),
    ]
