# Generated by Django 4.2.23 on 2025-07-11 08:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0025_remove_petitiontemplate_has_share_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='petition',
            name='bgcolor',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='petition',
            name='gradient_from',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='petition',
            name='gradient_to',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='bgcolor',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='gradient_from',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='petitiontemplate',
            name='gradient_to',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
    ]
