# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0025_auto_20181031_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitiontemplate',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
    ]
