# Generated by Django 2.2 on 2019-04-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0026_auto_20190416_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.Petition')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.SlugModel')),
            ],
        ),
    ]
