# Generated by Django 4.2.23 on 2025-07-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0026_organization_moderated_alter_petition_bgcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratedElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderated_organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.organization')),
                ('moderated_petitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.petition')),
                ('moderated_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.pytitionuser')),
            ],
        ),
    ]
