# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0026_auto_20181031_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitiontemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
