# Generated by Django 4.2.23 on 2025-07-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0027_moderatedelements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeratedElements',
            new_name='ModeratedElement',
        ),
    ]
