# Generated by Django 4.2.23 on 2025-07-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0028_rename_moderatedelements_moderatedelement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderatedelement',
            options={'managed': False, 'verbose_name': 'Spam monitoring page'},
        ),
    ]
