# Generated by Django 2.2 on 2019-04-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0029_auto_20190417_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='slugs',
        ),
    ]
