# Generated by Django 4.2.23 on 2025-07-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0029_alter_moderatedelement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderatedelement',
            options={'managed': False, 'verbose_name_plural': 'Spam monitoring page'},
        ),
        migrations.AddField(
            model_name='pytitionuser',
            name='moderation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='petition.moderationreason'),
        ),
    ]
