# Generated by Django 4.2.23 on 2025-07-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0030_alter_moderatedelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytitionuser',
            name='moderation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petition.moderationreason'),
        ),
    ]
