# Generated by Django 4.2.23 on 2025-07-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0032_alter_pytitionuser_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytitionuser',
            name='moderation',
        ),
    ]
