# Generated by Django 2.2 on 2019-04-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0032_auto_20190417_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slugmodel',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='slugmodel',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slugname'),
        ),
        migrations.AddConstraint(
            model_name='slugownership',
            constraint=models.UniqueConstraint(condition=models.Q(user=None), fields=('slug', 'organization'), name='unique_slugnameperorg'),
        ),
        migrations.AddConstraint(
            model_name='slugownership',
            constraint=models.UniqueConstraint(condition=models.Q(organization=None), fields=('slug', 'user'), name='unique_slugnameperuser'),
        ),
    ]
