# Generated by Django 2.2 on 2019-04-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0033_auto_20190417_1732'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slugmodel',
            name='unique_slugname',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='slugs',
        ),
        migrations.AddField(
            model_name='slugmodel',
            name='petition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='petition.Petition'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SlugOwnership',
        ),
    ]
