# Generated by Django 4.2.23 on 2025-07-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0033_remove_pytitionuser_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='petition.pytitionuser'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='petition.petition'),
        ),
    ]
