# Generated by Django 2.2 on 2019-04-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0034_auto_20190419_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='petition_templates',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='petitions',
        ),
        migrations.RemoveField(
            model_name='pytitionuser',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='pytitionuser',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='pytitionuser',
            name='petition_templates',
        ),
        migrations.RemoveField(
            model_name='pytitionuser',
            name='petitions',
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.PytitionUser', verbose_name='User related to these permissions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.PytitionUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petitiontemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.PytitionUser'),
            preserve_default=False,
        ),
    ]
