# Generated by Django 4.2.23 on 2025-07-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0034_moderation_user_alter_moderation_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='petition.organization'),
        ),
    ]
