# Generated by Django 2.2 on 2019-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0035_auto_20190419_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='petition.Permission', to='petition.PytitionUser'),
        ),
    ]
