# Generated by Django 4.2.23 on 2025-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0035_moderation_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='check_signatures_at_creation',
            field=models.BooleanField(default=False),
        ),
    ]
