# Generated by Django 4.2.23 on 2025-07-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0036_petition_check_signatures_at_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='message')),
                ('priority', models.TextField(verbose_name='priority')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='petition',
            name='monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='petition.petition')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petition.monitoringreason')),
            ],
        ),
    ]
