# Generated by Django 4.2.23 on 2025-07-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0037_monitoringreason_petition_monitored_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='cron_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
