# Generated by Django 2.2 on 2019-04-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0037_auto_20190419_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateOwnership',
        ),
    ]
