# Generated by Django 2.2 on 2019-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0038_delete_templateownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='can_create_petitions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_create_templates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_modify_petitions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_modify_templates',
            field=models.BooleanField(default=True),
        ),
    ]
