# Generated by Django 4.2.23 on 2025-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0038_petition_cron_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytitionuser',
            name='ipaddr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pytitionuser',
            name='user_agent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
