# Generated by Django 4.2.23 on 2025-07-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0039_pytitionuser_ipaddr_pytitionuser_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='petition.petition'),
        ),
    ]
