# Generated by Django 4.2.23 on 2025-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0040_alter_moderation_petition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='cron_scheduled',
            new_name='cron_to_schedule',
        ),
        migrations.RemoveField(
            model_name='pytitionuser',
            name='ipaddr',
        ),
        migrations.RemoveField(
            model_name='pytitionuser',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='petition',
            name='ipaddr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='user_agent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
