# Generated by Django 4.2.23 on 2025-08-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0041_rename_cron_scheduled_petition_cron_to_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='petition.organization'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='petition.pytitionuser'),
        ),
        migrations.AddField(
            model_name='pytitionuser',
            name='monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='petition.petition'),
        ),
    ]
