# Generated by Django 4.2.23 on 2025-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0042_monitoring_org_monitoring_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='monitored',
            field=models.BooleanField(default=False),
        ),
    ]
