# Generated by Django 4.2.23 on 2025-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0043_organization_monitored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringreason',
            name='priority',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='priority',
            field=models.TextField(blank=True, verbose_name='priority'),
        ),
    ]
