# Generated by Django 4.2.23 on 2025-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0044_remove_monitoringreason_priority_monitoring_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationreason',
            name='msg',
            field=models.TextField(unique=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='monitoringreason',
            name='msg',
            field=models.TextField(unique=True, verbose_name='message'),
        ),
    ]
