# Generated by Django 4.2.24 on 2025-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0045_alter_moderationreason_msg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='check_signatures_at_creation',
            new_name='check_signatures_at_each_signature',
        ),
        migrations.AddField(
            model_name='petition',
            name='in_bin',
            field=models.BooleanField(default=False),
        ),
    ]
