# Generated by Django 4.2.24 on 2025-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0046_rename_check_signatures_at_creation_petition_check_signatures_at_each_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='in_bin',
        ),
        migrations.AddField(
            model_name='petition',
            name='in_bin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
