# Generated by Django 4.2.25 on 2025-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0047_remove_petition_in_bin_petition_in_bin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='ipaddr',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
