# Generated by Django 4.2.25 on 2025-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0048_alter_petition_ipaddr_alter_petition_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
