# Generated by Django 5.2.7 on 2025-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0049_alter_petition_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitiontemplate',
            name='paper_signatures',
            field=models.IntegerField(default=0),
        ),
    ]
