from django.conf.urls import url, include
from django.urls import path

from . import views
from .forms import PytitionUserCreationForm
from .views import PetitionCreationWizard
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<petition_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<petition_id>[0-9]+)/confirm/(?P<confirmation_hash>.*)$', views.confirm, name='confirm'),
    url(r'^(?P<petition_id>[0-9]+)/get_csv_signature$', views.get_csv_signature, {'only_confirmed': False},
        name='get_csv_signature'),
    url(r'^(?P<petition_id>[0-9]+)/get_csv_confirmed_signature$', views.get_csv_signature, {'only_confirmed': True},
        name='get_csv_confirmed_signature'),
    url(r'^resend/(?P<signature_id>[0-9]+)', views.go_send_confirmation_email, name='resend_confirmation_email'),
    url(r'^(?P<petition_id>[0-9]+)/sign', views.create_signature, name='create_signature'),
    url(r'^(?P<petition_id>[0-9]+)/show_signatures', views.show_signatures, name='show_signatures'),
    url(r'^petition_delete', views.petition_delete, name='petition_delete'),
    url(r'^petition_publish', views.petition_publish, name='petition_publish'),
    url(r'^petition_unpublish', views.petition_unpublish, name='petition_unpublish'),
    path('org/<slug:orgslugname>', views.org_profile, name='org_profile'),
    path('org/<slug:orgslugname>/dashboard', views.org_dashboard, name='org_dashboard'),
    url(r'^leave_org$', views.leave_org, name="leave_org"),
    path('org/<slug:orgslugname>/add_user', views.org_add_user, name='org_add_user'),
    path('org/<slug:orgslugname>/new_template', views.new_template, name='org_new_template'),
    url(r'^edit_template/(?P<template_id>[^/]+)$', views.edit_template, name='edit_template'),
    url(r'^ptemplate_fav_toggle$', views.ptemplate_fav_toggle, name='ptemplate_fav_toggle'),
    path('org/<slug:orgslugname>)/delete_member', views.org_delete_member, name='org_delete_member'),
    path('org/<slug:orgslugname>/edit_user_permissions/<slug:user_name>', views.org_edit_user_perms,
        name='org_edit_user_perms'),
    path('org/<slug:orgslugname>/set_user_permissions/<slug:user_name>', views.org_set_user_perms,
        name='org_set_user_perms'),
    url(r'^edit_petition/(?P<petition_id>[0-9]+)$', views.edit_petition,
        name='edit_petition'),
    url(r'^user/dashboard$', views.user_dashboard, name='user_dashboard'),
    url(r'^user/new_template$', views.new_template, name='user_new_template'),
    url(r'^user/(?P<user_name>[^/]+)$', views.user_profile, name='user_profile'),
    url(r'^template_delete$', views.template_delete, name='template_delete'),
    url(r'^get_user_list', views.get_user_list, name='get_user_list'),
    url(r'^invite_accept/$', views.invite_accept, name='invite_accept'),
    url(r'^invite_dismiss/$', views.invite_dismiss, name='invite_dismiss'),
    path('wizard/org/<slug:orgslugname>/new_petition', PetitionCreationWizard.as_view(views.WizardForms),
        name='org_petition_wizard'),
    path('wizard/org/<slug:orgslugname>/new_petition/from_template/<int:template_id>', PetitionCreationWizard.as_view(views.WizardForms),
        name='org_petition_wizard_from_template'),
    url(r'^wizard/user/new_petition$', PetitionCreationWizard.as_view(views.WizardForms),
        name='user_petition_wizard'),
    url(r'^wizard/user/new_petition/from_template/(?P<template_id>[^/]+)$', PetitionCreationWizard.as_view(views.WizardForms),
        name='user_petition_wizard_from_template'),
    url('^', include('django.contrib.auth.urls')),
    url('^register/',
        CreateView.as_view(template_name='registration/register.html', form_class=PytitionUserCreationForm,
                           success_url=reverse_lazy("login")), name="register"),
    url('^account_settings$', views.account_settings, name="account_settings"),
    url('^org_create$', views.org_create, name="org_create"),
    path('org/<slug:orgslugname>/<slug:petitionname>', views.slug_show_petition, name="slug_show_petition"),
    path('user/<slug:username>/<slug:petitionname>', views.slug_show_petition, name="slug_show_petition"),
    path('<int:petition_id>/add_new_slug', views.add_new_slug, name="add_new_slug"),
    path('<int:petition_id>/del_slug', views.del_slug, name="del_slug"),
]